CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(

    NOME_DO_LIVRO VARCHAR(30),
    NOME_DO_AUTOR VARCHAR(30),
    SEXO_DO_AUTOR VARCHAR(9),
    NUMERO_DE_PAGINAS INT(4),
    NOME_DA_EDITORA VARCHAR(20),
    VALOR_DO_LIVRO DECIMAL(10,2),
    UF VARCHAR(2),
    ANO_DE_PUBLICACAO INT(4)
);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('CAVALEIRO REAL','ANA CLAUDIA','FEMININO',465,'ATLAS',49.9,'RJ',2009);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('SQL PARA LEIGOS','JOÃO NUNES','MASCULINO',450,'ADDISON',98,'SP',2018);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('RECEITAS CASEIRAS','CELIA TAVARES','FEMININO',210,'ATLAS',45,'RJ',2008);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('PESSOAS EFETIVAS','EDUARDO SANTOS','MASCULINO',390,'BETA',78.99,'RJ',2018);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('HABITOS SAUDAVEIS','EDUARDO SANTOS','MASCULINO',630,'BETA',150.98,'RJ',2019);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('A CASA MARROM','HERMES MACEDO','MASCULINO',250,'BUBBA',60,'MG',2016);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('ESTACIO QUERIDO ','GERALDO FRANCISCO','MASCULINO',310,'INSIGNIA',100,'ES',2015);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('PARA SEMPRE AMIGAS','LEDA SILVA','FEMININO',510,'INSIGNIA',78.98,'ES',2011);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('COPAS INESQUECIVEIS','MARCO ALCANTARA','MASCULINO',200,'LARSON',130.98,'RS',2018);

INSERT INTO LIVROS(NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,UF,ANO_DE_PUBLICACAO) 
    VALUES('O PODER DA MENTE','CLARA MAFRA','FEMININO',120,'CONTINENTAL',56.58,'SP',2017);



    -- TRAZER TODOS OS DADOS

    SELECT * FROM LIVROS;

    -- TRAZER NOME DO LIVRO EO NOME DA EDITORA

    SELECT NOME_DO_LIVRO , NOME_DA_EDITORA FROM LIVROS;

    -- TRAZER NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO

    SELECT NOME_DO_LIVRO, UF FROM LIVROS WHERE SEXO_DO_AUTOR = 'MASCULINO';

    -- TRAZER NOME DO LIVRO E 0 NUMERO DE PAGIAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO

     SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS WHERE SEXO_DO_AUTOR = 'FEMININO';

     --TRAZE OS VALORES DOS LIVROS DAS EDITORAS DE SAO PAULO 

     SELECAO VALOR_DO_LIVRO FROM LIVROS WHERE UF = 'SP';

     -- TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SAP OU RJ 

SELECT NOME_DO_AUTOR FROM LIVROS WHERE SEXO_DO_AUTOR = 'MASCULINO' AND (UF ='SP' OR UF ='RJ');
