USE PROJETO;

-- CLIENTE PUSSI VARIOS TELEFONES E CLIENTE POSSUI UM ENDERECO
-- 1 PRA 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA
-- 1 PRA N A CHAVE ESTRANGEIRA FICA NA CARTINALIDADE N

--guincho_id INT NOT NULL: Cria a coluna que servirá como chave estrangeira.
--FOREIGN KEY (guincho_id) REFERENCES guinchos(id): Define a relação com a tabela guinchos, ligando guincho_id ao id da outra tabela.
--ON DELETE CASCADE: Se um guincho for excluído, todos os atendimentos vinculados a ele também serão removidos.

DROP TABLE CLIENTE;


CREATE TABLE CLIENTE (

    IDCLIENTE INT  AUTO_INCREMENT PRIMARY KEY   NOT NULL UNIQUE,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F'),
    EMAIL VARCHAR(50) UNIQUE,
    CPF VARCHAR(15) UNIQUE

);

CREATE TABLE ENDERECO(

    IDENDERECO INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    RUA VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL
    IDCLIENTE INT NOT NULL UNIQUE,

    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE) DELETE ON CASCADE


);


CREATE TABLE TELEFONE(

    IDTELEFONE INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    TIPO ENUM('RES','COM','CEL') NOT  NULL,
    NUMERO VARCHAR(10) NOT NULL,
    IDCLIENTE INT NOT NULL,

    FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)

);



INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');


INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);


INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','CENTRO','SAO PAULO','SP',5);



INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);


DESC TELEFONE;

SELECT NOME, SEXO, EMAIL /* PROJECAO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELECAO */

SELECT NUMERO /* PROJECAO */
FROM TELEFONE /* ORIGEM */
WHERE TIPO = 'CEL'; /* SELECAO */

select IDCLIENTE,COUNT(*) from TELEFONE GROUP BY IDCLIENTE;
SELECT IDCLIENTE,COUNT(*) AS QUANT FROM TELEFONE GROUP BY IDCLIENTE ORDER BY QUANT;

SELECT id, departamento, salario
FROM funcionarios
ORDER BY departamento ASC, salario DESC;


-- JUNCAO 