/* Modelagem  Básica 

 ENTIDADE = TABELA
 CAMPOS = ATRIBUTOS

CLIENTE

NOME - CARACTER (30)
CPF  - NUMERICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDERECO - CARACTER (100)
SEXO - CARACTER (1)

 PROCESSOS DE MODELAGEM  

CONCEITUAL = RASCUNHO , LÓGICA = QUALQUER PROGRAMA DE MODELAGEM , FÍSICA = DBA / AD 


INICIANDO A MODELAGEM FÍSICA 


CRIANDO BANCO DE DADOS

*/

CREATE DATABASE PROJETO;

CREATE DATABASE EXEMPLO;

/* CONECTANDO AO BANCO */

USE PROJETO;

/*CRIANDO TABELA*/

CREATE TABLE CLIENTE(

    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECI VARCHAR(100)

);

SELECT * FROM CLIENTE;

SHOW TABLES; 

DESC CLIENTE;


/*EXCLUINDO COLUNAS*/

INSERT INTO CLIENTE VALUES ('JOAO','M','JAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO PATOS DE MINAS - MG');

/*COLOCANDO AS COLUNAS*/

INSERT INTO CLIENTE(NOME,SEXO,ENDERECI,TELEFONE,CPF) VALUES ('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);


ALTER TABLE CLIENTE CHANGE ENDERECI ENDERECO VARCHAR(100);


/*COMANDO SELECT   PROJECAO , SELECAO E CONJUNTO*/

SELECT NOW() AS DATA_HORA , 'RAFAEL' AS 'PROFESSOR';

SELECT 'RAFAEL';

/*ALIAS DE COLUNAS*/

SELECT NOME , SEXO , EMAIL FROM CLIENTE;

SELECT NOME , SEXO , EMAIL , ENDERECO  FROM CLIENTE;

SELECT NOME AS CLIENTE , SEXO , EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT NOME AS CLIENTE , SEXO , EMAIL , NOW() AS DATA_HORA FROM CLIENTE;

/*FILTROS*/

SELECT NOME, TELEFONE FROM CLIENTE;


SELECT NOME, TELEFONE FROM CLIENTE
WHERE SEXO='M';

SELECT NOME AS CLIENTE,TELEFONE, NOW() AS DATA_HORA FROM CLIENTE -- FILTRA COLUNA
WHERE SEXO='F'; -- FILTRA LINHA

SELECT NOME AS CLIENTE,TELEFONE, NOW() AS DATA_HORA FROM CLIENTE -- FILTRA COLUNA
WHERE ENDERECO LIKE '%RJ%'; -- FILTRA LINHA


/*


USE PROJETO;

CREATE TABLE CLIENTE(

    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECI VARCHAR(100)
    
);

SELECT * FROM CLIENTE;

SHOW TABLES;

DESC CLIENTE;

INSERT INTO CLIENTE VALUES ('JOAO','M','JAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO PATOS DE MINAS - MG');


INSERT INTO CLIENTE(NOME,SEXO,ENDERECI,TELEFONE,CPF) VALUES ('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

ALTER TABLE CLIENTE CHANGE ENDERECI ENDERECO VARCHAR(100);


SELECT NOW();
SELECT NOW() AS DATA_HORA,'RAFAEL' AS 'PROFESSOR';

SELECT 'RAFAEL';



SELECT NOME , SEXO , EMAIL FROM CLIENTE;

SELECT NOME , SEXO , EMAIL , ENDERECO  FROM CLIENTE;

SELECT NOME AS CLIENTE , SEXO , EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT NOME AS CLIENTE , SEXO , EMAIL , NOW() AS DATA_HORA FROM CLIENTE;



SELECT NOME, TELEFONE FROM CLIENTE
WHERE SEXO='M';

SELECT NOME AS CLIENTE, TELEFONE ,NOW() AS DATA_HORA FROM CLIENTE
WHERE SEXO='F';


SELECT NOME AS CLIENTE, ENDERECO , NOW() AS DATA_HORA FROM CLIENTE
WHERE ENDERECO  LIKE '%RJ%';





*/